apiVersion: apps/v1
kind: Deployment
metadata:
  name: codigo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codigo-deployment
  template:
    metadata:
      labels:
        app: codigo-deployment
    spec:
      containers:
        - name: codigo-deployment
          image: fernandoper501/pep3tingeso_codigoservice:latest
          ports:
            - containerPort: 8082
          env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://postgresql:5432/PEP3_Tingeso
          - name: SPRING_DATASOURCE_USERNAME
            value: "postgres"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "1234"
---
apiVersion: v1
kind: Service
metadata:
  name: codigo-service
  labels:
    app: codigo-deployment # Debe coincidir con el deployment
spec:
  selector:
    app: codigo-deployment # Debe coincidir con el deployment
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082