apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-deployment
  template:
    metadata:
      labels:
        app: config-deployment
    spec:
      containers:
        - name: config-deployment
          image: fernandoper501/pep3tingeso_configservice:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    app: config-deployment # Debe coincidir con el deployment
spec:
  selector:
    app: config-deployment # Debe coincidir con el deployment
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081