apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-deployment
  template:
    metadata:
      labels:
        app: eureka-deployment
    spec:
      containers:
        - name: eureka-deployment
          image: fernandoper501/pep3tingeso_eurekaservice:latest
          ports:
            - containerPort: 8761
          env:
            - name: spring.cloud.config.uri
              value: http://config-service:8081
            - name: spring.config.import
              value: optional:configserver:http://config-service:8081
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    app: eureka-deployment # Debe coincidir con el deployment
spec:
  selector:
    app: eureka-deployment # Debe coincidir con el deployment
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761