apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-deployment
  template:
    metadata:
      labels:
      app: gateway-deployment
    spec:
      containers:
        - name: gateway-deployment
          image: fernandoper501/pep3tingeso_gatewayservice:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: gateway-deployment # Debe coincidir con el deployment
spec:
  selector:
    app: gateway-deployment # Debe coincidir con el deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080